version: "3.8"
services:
  perftests_1:
    image: perftests:latest
    env_file:
      - docker-compose.env
    volumes:
      - scripts:/app/scripts/
  perftests_2:
    image: perftests:latest
    env_file:
      - docker-compose.env
    volumes:
      - scripts:/app/scripts/

volumes:
  scripts:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './test-scripts/'
